stages:
  - test
  - build
  - build-docker
  - deploy

test:
  image : node:14.0.0-slim
  stage: test
  script:
   - CI=true yarn test

build:
  image : node:14.0.0-slim
  stage: build
  script:
    - yarn
    - yarn run build
  artifacts:
    paths:
      - build


docker-build:
  image: docker:19.03.8
  stage: build-docker
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $DOCKER_ENV_CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_USER/$CI_DOCKER_REPOSITORY:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_USER/$CI_DOCKER_REPOSITORY:$CI_COMMIT_REF_SLUG"
  variables:
    DOCKER_HOST: tcp://localhost:2375
    DOCKER_TLS_CERTDIR: ""



deploy:
  stage: deploy
  image: bitnami/kubectl
  script:
    - docker pull "$CI_REGISTRY_USER/$CI_DOCKER_REPOSITORY:$CI_COMMIT_REF_SLUG"
    - kubectl apply -f deployment.yaml