stages:
  - test
  - build
  - deploy


image : node:14.0.0-slim

test:
  stage: test
  tags:
    - test
  script:
   - CI=true yarn test

build:
  stage: build
  tags:
    - build
  script:
    - yarn
    - yarn run build
  artifacts:
    expire_in: 1 hour
    paths:
      - build


pages:
  stage: deploy
  when: manual
  script:
    - mkdir .public
    - cp -r build/* .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - master