kind: Deployment
apiVersion: apps/v1
metadata:
  name: accidentes-aereos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accidentes-aereos
  template:
    metadata:
      labels:
        app: accidentes-aereos
    spec:
      containers:
        - name: accidentes-aereos:master
          image: localhost:5000/my-react-app
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: accidentes-aereos
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 80
  selector:
    app: my-react-app
